// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GudumholmIdærtAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241216025419_FixedUser6")]
    partial class FixedUser6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GudumholmIdærtAPI.Models.ActiveMemberSport", b =>
                {
                    b.Property<int>("ActiveMemberId")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("ActiveMemberId", "SportId");

                    b.HasIndex("SportId");

                    b.ToTable("ActiveMemberSports");
                });

            modelBuilder.Entity("GudumholmIdærtAPI.Models.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HouseId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CprNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentMemberMemberId")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.HasIndex("HouseId");

                    b.HasIndex("ParentMemberMemberId");

                    b.ToTable("Members", (string)null);

                    b.HasDiscriminator<string>("MemberType").HasValue("Member");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearlyFee")
                        .HasColumnType("int");

                    b.HasKey("SportId");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("ActiveMember", b =>
                {
                    b.HasBaseType("Member");

                    b.HasDiscriminator().HasValue("Active");
                });

            modelBuilder.Entity("BestyrelseMember", b =>
                {
                    b.HasBaseType("Member");

                    b.Property<int?>("SportId")
                        .HasColumnType("int");

                    b.HasIndex("SportId");

                    b.HasDiscriminator().HasValue("Bestyrelse");
                });

            modelBuilder.Entity("ParentMember", b =>
                {
                    b.HasBaseType("Member");

                    b.HasDiscriminator().HasValue("Parant");
                });

            modelBuilder.Entity("PassiveMember", b =>
                {
                    b.HasBaseType("Member");

                    b.Property<DateTime>("DateBecamePassive")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Passive");
                });

            modelBuilder.Entity("GudumholmIdærtAPI.Models.ActiveMemberSport", b =>
                {
                    b.HasOne("ActiveMember", "ActiveMember")
                        .WithMany("ActiveMemberSports")
                        .HasForeignKey("ActiveMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sport", "Sport")
                        .WithMany("ActiveMemberSports")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveMember");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.HasOne("GudumholmIdærtAPI.Models.House", "House")
                        .WithMany("Members")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParentMember", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentMemberMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("House");
                });

            modelBuilder.Entity("BestyrelseMember", b =>
                {
                    b.HasOne("Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("GudumholmIdærtAPI.Models.House", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Sport", b =>
                {
                    b.Navigation("ActiveMemberSports");
                });

            modelBuilder.Entity("ActiveMember", b =>
                {
                    b.Navigation("ActiveMemberSports");
                });

            modelBuilder.Entity("ParentMember", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
